In [1]:
import sys
import os

# Completely suppress stderr output
sys.stderr = open(os.devnull, 'w')

# Now import everything
import warnings
warnings.filterwarnings('ignore')

In [4]:
import pandas as pd

In [2]:
dataDir = '/mnt/data.ese/nfs/users/sghosh6/DTRA_project/MACAW/DrugDesignData/'
modelBuildingDataDir = os.path.join(dataDir, 'modelBuildingData/')
resultsDir = os.path.join(dataDir, 'Results/')

In [7]:
allVirusData_chEMBL_wMACAW_MLready = pd.read_csv(modelBuildingDataDir + 'allVirusData_chEMBL_wMACAW_MLready.csv')
allVirusData_chEMBL_wMACAW_MLready

,ID,compound_id,Smiles,pPotency,VirusClassifier
0,2,CHEMBL4065616,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,8.000000,SARS-CoV-2
1,3,CHEMBL4852507,C=CCn1ccc2c(C(=O)Oc3cncc(Cl)c3)cccc21,4.823909,SARS-CoV-2
2,4,CHEMBL4846056,CC(C)(C)OC(=O)N[C@@H](Cc1ccccc1)[C@@H](O)CN1CC...,4.997834,SARS-CoV-2
3,5,CHEMBL5419985,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1C[C@@H]2CC...,7.193820,SARS-CoV-2
4,6,CHEMBL46286,COC(=O)C[C@](O)(CCCC(C)(C)O)C(=O)O[C@@H]1C(OC)...,5.677781,SARS-CoV-2
...,...,...,...,...,...
4689,14493,CHEMBL5590446,CC1(C)[C@H]2CC[C@](C)(C2)[C@H]1OC(=O)CCCN1CCCCC1,5.337242,Marburg
4690,14494,CHEMBL5584026,CN1CCN(CC(=O)O[C@H]2C(C)(C)[C@H]3CC[C@]2(C)C3)CC1,4.602060,Marburg
4691,14495,CHEMBL1631748,O=c1c(/C=N/Cc2ccco2)c(CSc2ccc(Cl)cc2)[nH]n1-c1...,8.886057,Hanta
4692,14496,CHEMBL1630982,O=C(NCc1ccc2c(c1)OCO2)C(Cc1ccccc1)NS(=O)(=O)c1...,8.795880,Hanta
4693,14497,CHEMBL1631618,O=C(NCc1cccs1)C(Cc1ccccc1)NS(=O)(=O)c1ccc2nsnc2c1,8.602060,Hanta

In [9]:
first_entries = allVirusData_chEMBL_wMACAW_MLready.drop_duplicates(subset='VirusClassifier', keep='first').sort_values('VirusClassifier')
first_entries

,ID,compound_id,Smiles,pPotency,VirusClassifier
3444,13076,CHEMBL4751715,CCOP(=O)(Cc1cccc(COc2ccccc2OC2CCN(Cc3ccc4nc(-c...,5.725842,Ebola
4691,14495,CHEMBL1631748,O=c1c(/C=N/Cc2ccco2)c(CSc2ccc(Cl)cc2)[nH]n1-c1...,8.886057,Hanta
4091,13800,CHEMBL2314868,CCOc1ccc(Cn2cnc3cc(NCc4ccc(CC)cc4)cnc32)cc1,5.795880,Lassa
4505,14292,CHEMBL5593581,CN(C)C1CCN(C(=O)c2cc3ccccc3n2Cc2cccnc2)CC1,4.413413,Marburg
3291,12855,CHEMBL2016757,N#C[C@@]1(c2ccc3c(N)ncnn23)O[C@H](CO)[C@@H](O)...,5.673664,Nipah
4282,14017,CHEMBL201212,CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)NC(CCC(=O)N(...,5.443697,SARS-CoV
0,2,CHEMBL4065616,CCC(CC)COC(=O)[C@H](C)N[P@](=O)(OC[C@H]1O[C@@]...,8.000000,SARS-CoV-2
3301,12865,CHEMBL5088695,COc1ccc(Nc2ccnc3ccc(C(F)(F)F)cc23)c(OC)c1,5.468521,VEEV